/* Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

const evenNumbers = [];
let prevNum = 1;
let nextNum = 1;
let fibNum;

do {
  fibNum = prevNum + nextNum;
  prevNum = nextNum;
  nextNum = fibNum;
  if (fibNum % 2 === 0) {
    evenNumbers.push(fibNum);
  }
} while (fibNum < 4000000);

const totalSum = evenNumbers.reduce((a, b) => a + b);

// eslint-disable-next-line no-console
console.log(totalSum); // 4,613,732
